---
kind: pipeline
type: docker
name: test

steps:
- name: build
  image: alpine
  commands:
  - echo It works?!

- name: "build docker"
  image: plugins/docker
  settings:
    repo: ovdnet/test
    username:
      from_secret: docker_user
    password:
      from_secret: docker_password