---
kind: pipeline
type: docker
name: test

steps:
- name: "set image tags"
  image: bash
  commands:
    - "ls -la"
    - "bash .drone-write-tags.sh $DRONE_TAG > .tags"
    - "# Will build the following tags:"
    - "cat .tags"

trigger:
  event:
  - tag
  ref:
    exclude:
    - refs/tags/*alpha*
    - refs/tags/*dev*
